[project]
org-name = "ldclakmal"
version = "1.0.1"
authors = ["Chanaka Lakmal"]
keywords = ["sample-connector", "connector", "quickstart"]
repository = "https://github.com/ldclakmal/ballerina-connector-quickstart"
license = ["Apache-2.0"]

[dependencies]
